"""empty message

Revision ID: 22c9e37131e2
Revises: 
Create Date: 2021-09-25 20:13:12.928615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c9e37131e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_shooting',
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('fgp', sa.Float(), nullable=False),
    sa.Column('rar_fgm', sa.Float(), nullable=False),
    sa.Column('rar_fga', sa.Float(), nullable=False),
    sa.Column('rar_fgp', sa.Float(), nullable=False),
    sa.Column('itp_fgm', sa.Float(), nullable=False),
    sa.Column('itp_fga', sa.Float(), nullable=False),
    sa.Column('itp_fgp', sa.Float(), nullable=False),
    sa.Column('mrg_fgm', sa.Float(), nullable=False),
    sa.Column('mrg_fga', sa.Float(), nullable=False),
    sa.Column('mrg_fgp', sa.Float(), nullable=False),
    sa.Column('lc3_fgm', sa.Float(), nullable=False),
    sa.Column('lc3_fga', sa.Float(), nullable=False),
    sa.Column('lc3_fgp', sa.Float(), nullable=False),
    sa.Column('rc3_fgm', sa.Float(), nullable=False),
    sa.Column('rc3_fga', sa.Float(), nullable=False),
    sa.Column('rc3_fgp', sa.Float(), nullable=False),
    sa.Column('cn3_fgm', sa.Float(), nullable=False),
    sa.Column('cn3_fga', sa.Float(), nullable=False),
    sa.Column('cn3_fgp', sa.Float(), nullable=False),
    sa.Column('ab3_fgm', sa.Float(), nullable=False),
    sa.Column('ab3_fga', sa.Float(), nullable=False),
    sa.Column('ab3_fgp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('player')
    )
    op.create_table('team_matches',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fgp', sa.Float(), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('tpa', sa.Integer(), nullable=False),
    sa.Column('tpp', sa.Float(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('ftp', sa.Float(), nullable=False),
    sa.Column('oreb', sa.Integer(), nullable=False),
    sa.Column('dreb', sa.Integer(), nullable=False),
    sa.Column('reb', sa.Integer(), nullable=False),
    sa.Column('ast', sa.Integer(), nullable=False),
    sa.Column('stl', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('tov', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players_info',
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player'], ['players_shooting.player'], ),
    sa.PrimaryKeyConstraint('player')
    )
    op.create_table('players_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fgp', sa.Float(), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('tpa', sa.Integer(), nullable=False),
    sa.Column('tpp', sa.Float(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('ftp', sa.Float(), nullable=False),
    sa.Column('oreb', sa.Integer(), nullable=False),
    sa.Column('dreb', sa.Integer(), nullable=False),
    sa.Column('reb', sa.Integer(), nullable=False),
    sa.Column('ast', sa.Integer(), nullable=False),
    sa.Column('stl', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('tov', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['team_matches.match_id'], ),
    sa.ForeignKeyConstraint(['player'], ['players_shooting.player'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_matches')
    op.drop_table('players_info')
    op.drop_table('team_matches')
    op.drop_table('players_shooting')
    # ### end Alembic commands ###
