"""empty message

Revision ID: 734096e1fae0
Revises: f581a34dcdf3
Create Date: 2021-09-25 15:28:18.280671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '734096e1fae0'
down_revision = 'f581a34dcdf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_matches', 'player',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players_matches', 'team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players_matches', 'match',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('players_matches', 'won',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('players_matches', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'fgm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'fga',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_matches', 'tpm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'tpa',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'tpp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_matches', 'ftm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'fta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'ftp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_matches', 'oreb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'dreb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'reb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'ast',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'stl',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'blk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_matches', 'tov',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players_shooting', 'team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players_shooting', 'fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'rar_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'rar_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'rar_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'itp_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'itp_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'itp_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'mrg_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'mrg_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'mrg_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'lc3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'lc3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'lc3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'rc3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'rc3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'rc3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'cn3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'cn3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'cn3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'ab3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'ab3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('players_shooting', 'ab3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('team_matches', 'team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('team_matches', 'match',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('team_matches', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('team_matches', 'won',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('team_matches', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'fgm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'fga',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('team_matches', 'tpm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'tpa',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'tpp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('team_matches', 'ftm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'fta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'ftp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('team_matches', 'oreb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'dreb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'reb',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'ast',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'stl',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'blk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_matches', 'tov',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_matches', 'tov',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'blk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'stl',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'ast',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'reb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'dreb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'oreb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'ftp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('team_matches', 'fta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'ftm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'tpp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('team_matches', 'tpa',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'tpm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('team_matches', 'fga',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'fgm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_matches', 'won',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('team_matches', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_matches', 'match',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('team_matches', 'team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players_shooting', 'ab3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'ab3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'ab3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'cn3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'cn3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'cn3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'rc3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'rc3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'rc3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'lc3_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'lc3_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'lc3_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'mrg_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'mrg_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'mrg_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'itp_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'itp_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'itp_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'rar_fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'rar_fga',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'rar_fgm',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_shooting', 'team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players_matches', 'tov',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'blk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'stl',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'ast',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'reb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'dreb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'oreb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'ftp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_matches', 'fta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'ftm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'tpp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_matches', 'tpa',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'tpm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'fgp',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('players_matches', 'fga',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'fgm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'won',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('players_matches', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('players_matches', 'match',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players_matches', 'team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players_matches', 'player',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
