"""empty message

Revision ID: f581a34dcdf3
Revises: 23c7865ed963
Create Date: 2021-09-25 15:23:49.178113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f581a34dcdf3'
down_revision = '23c7865ed963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_shooting',
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('fgp', sa.Float(), nullable=True),
    sa.Column('rar_fgm', sa.Float(), nullable=True),
    sa.Column('rar_fga', sa.Float(), nullable=True),
    sa.Column('rar_fgp', sa.Float(), nullable=True),
    sa.Column('itp_fgm', sa.Float(), nullable=True),
    sa.Column('itp_fga', sa.Float(), nullable=True),
    sa.Column('itp_fgp', sa.Float(), nullable=True),
    sa.Column('mrg_fgm', sa.Float(), nullable=True),
    sa.Column('mrg_fga', sa.Float(), nullable=True),
    sa.Column('mrg_fgp', sa.Float(), nullable=True),
    sa.Column('lc3_fgm', sa.Float(), nullable=True),
    sa.Column('lc3_fga', sa.Float(), nullable=True),
    sa.Column('lc3_fgp', sa.Float(), nullable=True),
    sa.Column('rc3_fgm', sa.Float(), nullable=True),
    sa.Column('rc3_fga', sa.Float(), nullable=True),
    sa.Column('rc3_fgp', sa.Float(), nullable=True),
    sa.Column('cn3_fgm', sa.Float(), nullable=True),
    sa.Column('cn3_fga', sa.Float(), nullable=True),
    sa.Column('cn3_fgp', sa.Float(), nullable=True),
    sa.Column('ab3_fgm', sa.Float(), nullable=True),
    sa.Column('ab3_fga', sa.Float(), nullable=True),
    sa.Column('ab3_fgp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('player')
    )
    op.create_table('team_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('match', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Float(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('match', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Float(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match'], ['team_matches.id'], ),
    sa.ForeignKeyConstraint(['player'], ['players_info.player'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'players_info', 'players_shooting', ['player'], ['player'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players_info', type_='foreignkey')
    op.drop_table('players_matches')
    op.drop_table('team_matches')
    op.drop_table('players_shooting')
    # ### end Alembic commands ###
